export const PLATFORM_PERMISSIONS = [
  'platform:access',
  'platform:dashboard:view',
  'tenant:create',
  'tenant:view',
  'tenant:list',
  'tenant:update',
  'tenant:suspend',
  'tenant:delete',
  'tenant:impersonate',
  'plan:create',
  'plan:view',
  'plan:list',
  'plan:update',
  'plan:delete',
  'platform:user:view',
  'platform:user:list',
  'platform:user:update',
  'platform:user:disable',
  'platform:user:delete',
  'billing:view',
  'billing:update',
  'billing:manage',
  'system:settings:view',
  'system:settings:update',
  'audit:platform:view',
  'analytics:platform:view',
];

export const TENANT_PERMISSIONS = [
  'tenant:profile:view',
  'tenant:profile:update',
  'tenant:settings:view',
  'tenant:settings:update',
  'tenant:members:view',
  'tenant:members:list',
  'tenant:members:invite',
  'tenant:members:update',
  'tenant:members:remove',
  'tenant:roles:view',
  'tenant:roles:list',
  'tenant:roles:assign',
  'tenant:departments:view',
  'tenant:departments:list',
  'tenant:departments:create',
  'tenant:departments:update',
  'tenant:departments:delete',
  'tenant:teams:view',
  'tenant:teams:list',
  'tenant:teams:create',
  'tenant:teams:update',
  'tenant:teams:delete',
];

export const USER_PERMISSIONS = [
  'user:self:view',
  'user:self:update',
  'user:view',
  'user:list',
  'user:create',
  'user:update',
  'user:disable',
  'user:delete',
  'user:invite',
  'user:role:update',
  'user:team:update',
  'user:department:update',
];

export const GOAL_PERMISSIONS = [
  'goal:create',
  'goal:view',
  'goal:list',
  'goal:update',
  'goal:delete',
  'goal:assign',
  'goal:submit',
  'goal:approve',
  'goal:reject',
  'goal:reopen',
  'goal:status:update',
];

export const REPORTING_PERMISSIONS = [
  'dsr:create',
  'dsr:view',
  'dsr:list',
  'dsr:update',
  'dsr:delete',
  'dsr:submit',
  'dsr:approve',
  'dsr:reject',
  'dsr:reopen',
  'wsr:create',
  'wsr:view',
  'wsr:list',
  'wsr:update',
  'wsr:delete',
  'wsr:submit',
  'wsr:approve',
  'wsr:reject',
  'wsr:reopen',
  'report:create',
  'report:view',
  'report:list',
  'report:update',
  'report:delete',
  'report:generate',
  'report:download',
  'report:export',
  'report:daily:view',
  'report:weekly:view',
  'report:monthly:view',
  'report:quarterly:view',
  'report:yearly:view',
  'report:department:view',
  'report:team:view',
  'report:tenant:view',
  'report:org:view',
];

export const TEMPLATE_PERMISSIONS = [
  'template:view',
  'template:list',
  'template:create',
  'template:update',
  'template:delete',
  'template:platform:create',
  'template:platform:view',
  'template:platform:list',
  'template:platform:update',
  'template:platform:delete',
  'template:tenant:create',
  'template:tenant:view',
  'template:tenant:list',
  'template:tenant:update',
  'template:tenant:delete',
  'template:assign',
  'template:clone',
  'template:publish',
];

export const APPROVAL_PERMISSIONS = [
  'approval:view',
  'approval:list',
  'approval:dsr',
  'approval:wsr',
  'approval:goal',
  'approval:report',
];

export const ANALYTICS_PERMISSIONS = [
  'dashboard:self:view',
  'dashboard:team:view',
  'dashboard:department:view',
  'dashboard:tenant:view',
  'analytics:self:view',
  'analytics:team:view',
  'analytics:department:view',
  'analytics:tenant:view',
  'kpi:view',
  'trend:view',
  'productivity:view',
  'performance:view',
];

export const AI_PERMISSIONS = [
  'ai:access',
  'ai:dsr:generate',
  'ai:wsr:generate',
  'ai:goal:generate',
  'ai:report:generate',
  'ai:summary:generate',
  'ai:insight:view',
  'ai:recommendation:view',
  'ai:risk:predict',
  'ai:productivity:view',
  'ai:performance:view',
  'ai:prompt:use',
  'ai:history:view',
  'ai:feedback:create',
];

export const INTEGRATION_PERMISSIONS = [
  'integration:view',
  'integration:list',
  'integration:create',
  'integration:update',
  'integration:delete',
  'integration:github:connect',
  'integration:github:disconnect',
  'integration:github:sync',
  'integration:jira:connect',
  'integration:jira:disconnect',
  'integration:jira:sync',
  'integration:slack:connect',
  'integration:slack:disconnect',
  'integration:slack:sync',
  'integration:webhook:create',
  'integration:webhook:update',
  'integration:webhook:delete',
  'integration:webhook:view',
];

export const NOTIFICATION_PERMISSIONS = [
  'notification:self:view',
  'notification:self:update',
  'notification:tenant:view',
  'notification:tenant:manage',
];

export const BLOCKER_PERMISSIONS = [
  'blocker.create',
  'blocker.assign',
  'blocker.escalate',
  'blocker.resolve',
];

export const REPORT_INSTANCE_PERMISSIONS = [
  'report.submit',
  'report.view_all',
  'report.approve',
  'report.reject',
];

export const SECURITY_PERMISSIONS = [
  'audit:view',
  'audit:export',
  'security:view',
  'security:manage',
  'session:view:self',
  'session:revoke:self',
  'session:view:any',
  'session:revoke:any',
  'mfa:view',
  'mfa:manage',
  'apiKey:view',
  'apiKey:create',
  'apiKey:update',
  'apiKey:delete',
];

export const AUTOMATION_PERMISSIONS = [
  'automation:view',
  'automation:create',
  'automation:update',
  'automation:delete',
  'automation:execute',
];

export const ALL_PERMISSIONS = [
  ...PLATFORM_PERMISSIONS,
  ...TENANT_PERMISSIONS,
  ...USER_PERMISSIONS,
  ...GOAL_PERMISSIONS,
  ...REPORTING_PERMISSIONS,
  ...TEMPLATE_PERMISSIONS,
  ...APPROVAL_PERMISSIONS,
  ...ANALYTICS_PERMISSIONS,
  ...AI_PERMISSIONS,
  ...INTEGRATION_PERMISSIONS,
  ...NOTIFICATION_PERMISSIONS,
  ...SECURITY_PERMISSIONS,
  ...BLOCKER_PERMISSIONS,
  ...REPORT_INSTANCE_PERMISSIONS,
  ...AUTOMATION_PERMISSIONS,
];