import {
  ALL_PERMISSIONS,
  TENANT_PERMISSIONS,
  USER_PERMISSIONS,
  GOAL_PERMISSIONS,
  REPORTING_PERMISSIONS,
  TEMPLATE_PERMISSIONS,
  APPROVAL_PERMISSIONS,
  ANALYTICS_PERMISSIONS,
  AI_PERMISSIONS,
  INTEGRATION_PERMISSIONS,
  NOTIFICATION_PERMISSIONS,
  SECURITY_PERMISSIONS,
} from './permissions.js';

export const DEFAULT_ROLES = [
  {
    name: 'Platform Super Admin',
    description: 'Full platform access across tenants, templates, billing, audit, analytics, and security.',
    isPlatformRole: true,
    permissions: [...ALL_PERMISSIONS],
  },

  {
    name: 'Platform Support Admin',
    description: 'Platform operations and support access with limited destructive permissions.',
    isPlatformRole: true,
    permissions: [
      'platform:access',
      'platform:dashboard:view',
      'tenant:view',
      'tenant:list',
      'tenant:update',
      'platform:user:view',
      'platform:user:list',
      'platform:user:update',
      'billing:view',
      'audit:platform:view',
      'analytics:platform:view',
      'system:settings:view',
      'security:view',
      'session:view:any',
      'session:revoke:any',
      'template:platform:view',
      'template:platform:list',
      'template:tenant:view',
      'template:tenant:list',
    ],
  },

  {
    name: 'Tenant Owner',
    description: 'Highest authority within a tenant.',
    isPlatformRole: false,
    permissions: [
      ...TENANT_PERMISSIONS,
      ...USER_PERMISSIONS,
      ...GOAL_PERMISSIONS,
      ...REPORTING_PERMISSIONS,
      ...TEMPLATE_PERMISSIONS,
      ...APPROVAL_PERMISSIONS,
      ...ANALYTICS_PERMISSIONS,
      ...AI_PERMISSIONS,
      ...INTEGRATION_PERMISSIONS,
      ...NOTIFICATION_PERMISSIONS,
      ...SECURITY_PERMISSIONS,
    ],
  },

  {
    name: 'Tenant Admin',
    description: 'Manages tenant users, settings, reports, goals, dashboards, integrations, and tenant templates.',
    isPlatformRole: false,
    permissions: [
      ...TENANT_PERMISSIONS,
      ...USER_PERMISSIONS,
      ...GOAL_PERMISSIONS,
      ...REPORTING_PERMISSIONS,
      ...APPROVAL_PERMISSIONS,
      ...ANALYTICS_PERMISSIONS,
      ...AI_PERMISSIONS,
      ...INTEGRATION_PERMISSIONS,
      ...NOTIFICATION_PERMISSIONS,
      'template:view',
      'template:list',
      'template:tenant:create',
      'template:tenant:view',
      'template:tenant:list',
      'template:tenant:update',
      'template:tenant:delete',
      'template:assign',
      'template:clone',
      'template:publish',
      'audit:view',
      'audit:export',
      'security:view',
      'session:view:any',
      'session:revoke:any',
      'mfa:view',
    ],
  },

  {
    name: 'Department Head',
    description: 'Leads departments, monitors reports, goals, approvals, and department analytics.',
    isPlatformRole: false,
    permissions: [
      'tenant:departments:view',
      'tenant:departments:list',
      'tenant:teams:view',
      'tenant:teams:list',
      'user:view',
      'user:list',

      'goal:view',
      'goal:list',
      'goal:approve',
      'goal:reject',
      'goal:reopen',
      'goal:status:update',

      'dsr:view',
      'dsr:list',
      'dsr:approve',
      'dsr:reject',
      'dsr:reopen',

      'wsr:view',
      'wsr:list',
      'wsr:approve',
      'wsr:reject',
      'wsr:reopen',

      'report:view',
      'report:list',
      'report:generate',
      'report:download',
      'report:export',
      'report:weekly:view',
      'report:monthly:view',
      'report:quarterly:view',
      'report:yearly:view',
      'report:department:view',
      'report:team:view',

      'template:view',
      'template:list',
      'template:tenant:view',
      'template:tenant:list',

      'approval:view',
      'approval:list',
      'approval:goal',
      'approval:dsr',
      'approval:wsr',
      'approval:report',

      'dashboard:department:view',
      'dashboard:team:view',
      'analytics:department:view',
      'analytics:team:view',
      'kpi:view',
      'trend:view',
      'productivity:view',
      'performance:view',

      'ai:access',
      'ai:summary:generate',
      'ai:insight:view',
      'ai:recommendation:view',
      'ai:productivity:view',
      'ai:performance:view',
    ],
  },

  {
    name: 'Team Manager',
    description: 'Manages team goals, approvals, reports, and weekly visibility.',
    isPlatformRole: false,
    permissions: [
      'user:view',
      'user:list',

      'goal:create',
      'goal:view',
      'goal:list',
      'goal:update',
      'goal:assign',
      'goal:submit',
      'goal:approve',
      'goal:reject',
      'goal:reopen',
      'goal:status:update',

      'dsr:view',
      'dsr:list',
      'dsr:approve',
      'dsr:reject',
      'dsr:reopen',

      'wsr:view',
      'wsr:list',
      'wsr:approve',
      'wsr:reject',
      'wsr:reopen',

      'report:view',
      'report:list',
      'report:generate',
      'report:download',
      'report:weekly:view',
      'report:team:view',

      'template:view',
      'template:list',
      'template:tenant:view',
      'template:tenant:list',
      'template:assign',

      'approval:view',
      'approval:list',
      'approval:goal',
      'approval:dsr',
      'approval:wsr',

      'dashboard:team:view',
      'analytics:team:view',
      'kpi:view',
      'trend:view',
      'productivity:view',

      'ai:access',
      'ai:summary:generate',
      'ai:insight:view',
      'ai:recommendation:view',
    ],
  },

  {
    name: 'Employee',
    description: 'Standard contributor role for daily and weekly reporting and assigned goals.',
    isPlatformRole: false,
    permissions: [
      'user:self:view',
      'user:self:update',

      'goal:view',
      'goal:list',
      'goal:update',
      'goal:submit',

      'dsr:create',
      'dsr:view',
      'dsr:list',
      'dsr:update',
      'dsr:delete',
      'dsr:submit',

      'wsr:create',
      'wsr:view',
      'wsr:list',
      'wsr:update',
      'wsr:delete',
      'wsr:submit',

      'dashboard:self:view',
      'analytics:self:view',

      'notification:self:view',
      'notification:self:update',

      'session:view:self',
      'session:revoke:self',
      'mfa:view',
      'mfa:manage',

      'template:view',
      'template:list',
      'template:tenant:view',
      'template:tenant:list',

      'ai:access',
      'ai:dsr:generate',
      'ai:wsr:generate',
      'ai:goal:generate',
      'ai:summary:generate',
      'ai:prompt:use',
      'ai:history:view',
      'ai:feedback:create',
    ],
  },

  {
    name: 'Reviewer',
    description: 'Approval-only role for goals, DSR, WSR, and reports.',
    isPlatformRole: false,
    permissions: [
      'goal:view',
      'goal:list',
      'goal:approve',
      'goal:reject',
      'goal:reopen',

      'dsr:view',
      'dsr:list',
      'dsr:approve',
      'dsr:reject',
      'dsr:reopen',

      'wsr:view',
      'wsr:list',
      'wsr:approve',
      'wsr:reject',
      'wsr:reopen',

      'report:view',
      'report:list',

      'approval:view',
      'approval:list',
      'approval:goal',
      'approval:dsr',
      'approval:wsr',
      'approval:report',
    ],
  },

  {
    name: 'Auditor',
    description: 'Read-only audit, compliance, report, template, and security visibility.',
    isPlatformRole: false,
    permissions: [
      'audit:view',
      'audit:export',
      'security:view',
      'session:view:any',
      'report:view',
      'report:list',
      'report:download',
      'report:export',
      'report:daily:view',
      'report:weekly:view',
      'report:monthly:view',
      'report:quarterly:view',
      'report:yearly:view',
      'report:department:view',
      'report:team:view',
      'report:tenant:view',
      'template:view',
      'template:list',
      'template:tenant:view',
      'template:tenant:list',
      'dashboard:tenant:view',
      'analytics:tenant:view',
      'kpi:view',
      'trend:view',
      'productivity:view',
      'performance:view',
    ],
  },

  {
    name: 'HR Manager',
    description: 'People and performance visibility role.',
    isPlatformRole: false,
    permissions: [
      'user:view',
      'user:list',
      'goal:view',
      'goal:list',
      'report:view',
      'report:list',
      'report:generate',
      'report:download',
      'report:department:view',
      'report:tenant:view',
      'dashboard:department:view',
      'dashboard:tenant:view',
      'analytics:department:view',
      'analytics:tenant:view',
      'kpi:view',
      'trend:view',
      'productivity:view',
      'performance:view',
      'ai:access',
      'ai:summary:generate',
      'ai:insight:view',
      'ai:productivity:view',
      'ai:performance:view',
    ],
  },

  {
    name: 'Read Only Analyst',
    description: 'Read-only dashboards, reports, trends, and template visibility.',
    isPlatformRole: false,
    permissions: [
      'report:view',
      'report:list',
      'report:download',
      'report:daily:view',
      'report:weekly:view',
      'report:monthly:view',
      'report:quarterly:view',
      'report:yearly:view',
      'template:view',
      'template:list',
      'template:tenant:view',
      'template:tenant:list',
      'dashboard:self:view',
      'dashboard:team:view',
      'dashboard:department:view',
      'analytics:self:view',
      'analytics:team:view',
      'analytics:department:view',
      'kpi:view',
      'trend:view',
      'productivity:view',
      'performance:view',
    ],
  },
];