/**
 * AIRecommendation model. Stores recommendation artifacts generated by AI.
 */

import mongoose from "mongoose";
import { toJSONPlugin } from "../plugins/toJSON.plugin.js";

const schema = new mongoose.Schema(
  {
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Tenant",
      required: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true
    },
    targetType: {
      type: String,
      default: null,
      trim: true,
      index: true
    },
    targetId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
      index: true
    },
    type: {
      type: String,
      required: true,
      trim: true,
      index: true
    },
    priority: {
      type: String,
      enum: ["low", "medium", "high", "critical"],
      default: "medium",
      index: true
    },
    suggestedAction: {
      type: String,
      default: null
    },
    reason: {
      type: String,
      default: null
    },
    status: {
      type: String,
      enum: ["open", "accepted", "dismissed", "expired"],
      default: "open",
      index: true
    },
    recommendation: {
      type: mongoose.Schema.Types.Mixed,
      default: null
    },
    confidence: {
      type: Number,
      min: 0,
      max: 1,
      default: null
    },
    tokensUsed: {
      type: Number,
      required: true,
      default: 0,
      min: 0
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    }
  },
  {
    strict: true,
    minimize: false,
    timestamps: true,
    optimisticConcurrency: true
  }
);

schema.plugin(toJSONPlugin);

schema.index({ tenantId: 1, type: 1, createdAt: -1 });
schema.index({ tenantId: 1, userId: 1, createdAt: -1 });
schema.index({ tenantId: 1, targetType: 1, targetId: 1, createdAt: -1 });

export default mongoose.model("AIRecommendation", schema);
